name "suse"
maintainer "Thomas Boerger"
maintainer_email "tboerger@tbpro.de"
license "Apache 2.0"
description "Installs/Configures suse"
long_description IO.read(File.join(File.dirname(__FILE__), "README.md"))
version "0.0.1"
depends "homeshick"
depends "sshkey"
depends "sudo"
depends "zypper"
depends "libvirt"
recipe "suse", "Installs/Configures suse"

supports "suse"
